exports.DB_SECRET_NAME = process.env.DB_SECRET_NAME;
exports.ORM_LAYER_PATH = process.env.ORM_LAYER_PATH;
exports.GET_PLAYER_COUNTS_FUNCTION_NAME = process.env.GET_PLAYER_COUNTS_FUNCTION_NAME;
exports.NUM_UPDATE_LAMBDAS = 500;
exports.REQS_PER_SECOND_MAX = 30;